apiVersion: container.gcp.gke.cloud.google.com/v1beta1
kind: Cluster
metadata:
  annotations:
  name: cluster-2 # name of gke cluster
spec:
  forProvider:
    initialNodeCount: 1
    location: us-central1 # add gcp region 
    minMasterVersion: "1.27.4-gke.900"
    network: gkevpc
    subnetwork: subnet3
    networkingMode: VPC_NATIVE
    ipAllocationPolicy:
    - servicesIpv4CidrBlock: 10.11.144.0/24
    nodeConfig:
    - machineType: e2-standard-4
      diskSizeGb: 512
   # removeDefaultNodePool: true
    privateClusterConfig:
    - enablePrivateEndpoint: true
      enablePrivateNodes: true
      masterIpv4CidrBlock: 172.16.10.16/28
   #   masterGlobalAccessConfig: true
    masterAuthorizedNetworksConfig:
    - cidrBlocks:
        - cidrBlock: "10.0.0.0/8"
          displayName: "Allowed Mgmt Range"
        - cidrBlock: "192.168.0.0/16"
          displayName: "On-premises Network"
